export const PROMPTS = [
  "Draw your favourite animal wearing a hat",
  "A cozy treehouse with fairy lights",
  "An underwater tea party",
  "A cat riding a skateboard",
  "Your dream garden",
  "A cloud shaped like something funny",
  "A tiny dragon baking cookies",
  "A robot walking a dog",
  "Sunset over a candy landscape",
  "A penguin at the beach",
  "An enchanted forest path",
  "A house made of books",
  "A friendly monster under the bed",
  "Your breakfast as a character",
  "A snail racing a turtle",
  "A wizard's messy desk",
  "A bird delivering mail",
  "An alien visiting a farm",
  "A superhero with a silly power",
  "Dancing mushrooms in the rain",
  "A sleeping fox in autumn leaves",
  "A ship sailing through clouds",
  "A frog prince at a ball",
  "Your pet as a secret agent",
  "A bicycle made of flowers",
  "An owl reading by candlelight",
  "Goldfish in outer space",
  "A haunted gingerbread house",
  "A bear having a picnic",
  "Mountains made of pillows",
  "A submarine shaped like a whale",
  "A fairy fixing a rainbow",
  "Your shoe as a tiny house",
  "A horse with butterfly wings",
  "Rainy day through a window",
  "A cactus wearing sunglasses",
  "An octopus juggling",
  "A ladybug's birthday party",
  "Northern lights over an igloo",
  "A mouse exploring a library",
  "A hot air balloon festival",
  "A gnome tending a garden",
  "Your hand holding something magical",
  "A lighthouse in a storm",
  "A chameleon on a rainbow",
  "A duck in a top hat",
  "An elephant painting a picture",
  "A mermaid's treasure collection",
  "Fireworks over a small town",
  "A bunny astronaut on the moon",
  "A steampunk teapot",
  "Butterflies migrating at sunset",
  "A fox and a crow sharing lunch",
  "A yeti making a snow angel",
  "A pirate map to something silly",
  "A hedgehog in a leaf boat",
  "A phoenix rising from campfire",
  "Jellyfish lanterns in the deep sea",
  "A deer wearing a scarf",
  "A miniature city in a terrarium",
  "Wolves howling at a disco ball",
  "A narwhal with a party hat",
  "A sloth in a hammock",
  "Bees building a honey castle",
  "A Viking ship on a calm lake",
  "Crystals growing in a cave",
  "A koala on a unicycle",
  "A treehouse connected by bridges",
  "Storm in a teacup",
  "A gecko climbing a skyscraper",
  "A polar bear in a flower field",
  "Koi fish in a puddle",
  "A witch's cat mixing potions",
  "A llama wearing a poncho",
  "A giant mushroom village",
  "Paper airplanes in a tornado",
  "A walrus at a jazz club",
  "A field of windmills at dusk",
  "An iguana surfing",
  "A cozy blanket fort",
  "A capybara spa day",
  "A peacock at a fashion show",
  "Origami animals coming to life",
  "A badger's underground kitchen",
  "A hummingbird and a flower talking",
  "Stargazing from a rooftop",
  "A raccoon's treasure hoard",
  "A panda playing in snow",
  "A lamp that lights up dreams",
  "A seal balancing the Earth",
  "Vines growing over an old car",
  "A flamingo ice skating",
  "Tide pools full of tiny worlds",
  "A squirrel's acorn collection",
  "A snowglobe with your town inside",
  "A crow wearing jewellery",
  "A platypus detective",
  "An otter floating with a book",
  "A sandcastle kingdom",
  "A moose in a canoe",
];

// ── Moriah Elizabeth Inspired Daily Prompts ─────────────────────────────────────
export const MORIAH_PROMPTS = [
  "Pickle the dinosaur wearing a ridiculous hat",
  "A cozy treehouse built for Georgie and Cousin Derp",
  "Derp hosting an underwater tea party",
  "Pickle riding a skateboard",
  "Bumblebear's dream garden full of flowers",
  "A cloud shaped like Pickle",
  "A tiny dragon baking cookies with Lemon",
  "A robot walking Georgie",
  "Sunset over a candy world where Derp lives",
  "Pickle the penguin at the beach",
  "An enchanted forest where Pickle discovers a new friend",
  "A house made of sketchbooks and squishies",
  "A friendly monster that Derp finds under the bed",
  "Your breakfast turned into a squishy character",
  "Pickle racing Derp in a snail vs turtle race",
  "Moriah's messy art desk after a mystery wheel challenge",
  "Georgie delivering mail",
  "An alien visiting Pickle's farm",
  "A superhero version of Derp with a useless power",
  "Dancing mushrooms with Pickle",
  "A sleepy fox cuddling with Georgie",
  "Pickle sailing through clouds",
  "Derp as a frog prince at a ball",
  "Your pet as a Moriah-style squishy character",
  "A bicycle made of flowers for Bumblebear",
  "An owl reading Moriah's sketchbook",
  "Goldfish floating through space with Pickle",
  "A haunted gingerbread house with Derp inside",
  "Pickle having a picnic",
  "Mountains made of pillows for Georgie to nap on",
  "A whale-shaped submarine with Pickle inside",
  "A fairy fixing a rainbow with Lemon",
  "Your shoe turned into a Pickle house",
  "A horse with butterfly wings that Derp rides",
  "Rainy day through Moriah's art room window",
  "A cactus that looks like Derp wearing sunglasses",
  "An octopus juggling squishies",
  "A birthday party for Georgie",
  "Northern lights over Pickle's igloo",
  "A mouse exploring Moriah's sketchbook library",
  "Hot air balloons shaped like Pickle and Derp",
  "A gnome helping Pickle garden",
  "Your hand holding a magical squishy",
  "A lighthouse where Derp watches storms",
  "A chameleon turning into Pickle colours",
  "A duck that looks suspiciously like Derp",
  "An elephant painting a Pickle portrait",
  "A mermaid collecting squishy treasures",
  "Fireworks celebrating Pickle's birthday",
  "A bunny astronaut meeting Pickle on the moon",
  "A steampunk teapot that Derp invented",
  "Butterflies landing on Bumblebear",
  "A fox and a crow having lunch with Georgie",
  "A yeti making snow angels with Pickle",
  "A pirate map drawn by Derp",
  "A hedgehog sailing in a leaf boat with Lemon",
  "A phoenix rising beside Pickle",
  "Jellyfish lanterns lighting Pickle's ocean",
  "A deer wearing one of Moriah's scarves",
  "A miniature Pickle city in a terrarium",
  "Wolves howling at a disco ball with Derp dancing",
  "A narwhal wearing a Derp party hat",
  "A sloth relaxing with Georgie",
  "Bees building a honey castle for Bumblebear",
  "A Viking Pickle ship on a calm lake",
  "Crystals growing in a cave Pickle explores",
  "A koala riding a unicycle with Derp",
  "Pickle's giant treehouse connected by bridges",
  "A storm inside Derp's teacup",
  "A gecko climbing Moriah's art studio",
  "A polar bear wandering into Pickle's flower field",
  "Koi fish swimming around Pickle",
  "Georgie mixing potions like a witch's cat",
  "A llama wearing Derp's poncho",
  "A giant mushroom village where Pickle lives",
  "Paper airplanes flying around Moriah's studio",
  "A walrus playing jazz for Derp",
  "Windmills spinning in Pickle's countryside",
  "An iguana surfing with Derp",
  "A cozy blanket fort for Georgie and Pickle",
  "Bumblebear having a relaxing spa day",
  "A peacock modelling outfits designed by Derp",
  "Origami animals coming to life in Moriah's sketchbook",
  "A badger cooking in Pickle's underground kitchen",
  "A hummingbird talking to Bumblebear",
  "Stargazing with Pickle and Georgie",
  "Derp's giant treasure hoard",
  "A panda playing in snow with Pickle",
  "A lamp that lights up Moriah's imagination",
  "A seal balancing the world while Derp watches",
  "Vines growing over Pickle's old car",
  "A flamingo ice skating with Georgie",
  "Tide pools where tiny Pickles live",
  "A squirrel collecting acorns for Pickle",
  "A snowglobe with Pickle's world inside",
  "A crow wearing jewellery that Derp collected",
  "A platypus detective investigating missing squishies",
  "An otter floating while reading Moriah's sketchbook",
  "A sandcastle kingdom ruled by Pickle",
  "A moose paddling Derp across a lake",
];
